### ISSUE TITLE
Celery workers not running in staging env

### ISSUE THREAD

**Issue by camallen** [zooniverse/hamlet#227]
Seems this is in a Crash state
`hamlet-staging-celery-7f957d476-wz6wf                      0/1     CrashLoopBackOff   202        17h`

```
$ kubectl logs -f caesar-staging-app-59d98b7579-2ggz9 -c caesar-staging-app
...
[tasks]
  . hamlet.celery.fetch_media_metadata
  . hamlet.celery.ml_subject_assistant_export_to_microsoft
  . hamlet.celery.subject_set_export
  . hamlet.celery.update_subject_set_export_status
  . hamlet.celery.workflow_export
  . hamlet.celery.write_subject_set_export

[2020-06-20 09:21:37,324: INFO/MainProcess] Connected to redis://hamlet-staging-redis:6379//
[2020-06-20 09:21:37,334: INFO/MainProcess] mingle: searching for neighbors
[2020-06-20 09:21:38,422: INFO/MainProcess] mingle: all alone
[2020-06-20 09:21:38,449: INFO/MainProcess] celery@hamlet-staging-celery-7f957d476-wz6wf ready.
[2020-06-20 09:21:38,449: ERROR/MainProcess] Process 'ForkPoolWorker-3' pid:12 exited with 'signal 9 (SIGKILL)'
[2020-06-20 09:21:38,470: CRITICAL/MainProcess] Unrecoverable error: WorkerLostError('Could not start worker processes')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/usr/local/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 599, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.7/site-packages/celery/worker/loops.py", line 59, in asynloop
    raise WorkerLostError('Could not start worker processes')
billiard.exceptions.WorkerLostError: Could not start worker processes
```

**Comment by adammcmaster** [comment]
Looks like this was fixed by #231.
